//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal.Controls {
    
    
    public partial class ScaleQuestionControlFrench {
        
        /// <summary>
        /// mmMessage_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmMessage_F;
        
        /// <summary>
        /// radAnswer5_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer5_F;
        
        /// <summary>
        /// radAnswer4_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer4_F;
        
        /// <summary>
        /// radAnswer3_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer3_F;
        
        /// <summary>
        /// radAnswer2_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer2_F;
        
        /// <summary>
        /// radAnswer1_F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer1_F;
    }
}
