//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal.Controls {
    
    
    public partial class ScaleQuestionControl {
        
        /// <summary>
        /// mmMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmMessage;
        
        /// <summary>
        /// radAnswer5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer5;
        
        /// <summary>
        /// radAnswer4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer4;
        
        /// <summary>
        /// radAnswer3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer3;
        
        /// <summary>
        /// radAnswer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer2;
        
        /// <summary>
        /// radAnswer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAnswer1;
    }
}
