//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Website.
        /// </summary>
        internal static string DonationReturntoSite {
            get {
                return ResourceManager.GetString("DonationReturntoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is important to us and we look forward to receiving your comments and will endeavor to respond to your request within 12-24 hours..
        /// </summary>
        internal static string Donation_Final1 {
            get {
                return ResourceManager.GetString("Donation_Final1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Done&quot; below, you acknowledge that you are aware that your personal information (contact information and feedback) is being collected and used by Great Canadian Casino Corporation (GCGC) on behalf of BCLC in accordance with British Columbia&apos;s Freedom of Information and Protection of Privacy Act. It will only be used for GCGC&apos;s reporting &amp; research purposes and to administer the guest feedback process..
        /// </summary>
        internal static string Donation_Final2 {
            get {
                return ResourceManager.GetString("Donation_Final2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information will NOT be sold, shared with third parties, or used for soliciting purposes. If you have any questions about this, please write to GCGC&apos;s Privacy Officer at 95 Schooner Street, Coquitlam, BC V3K 7A8..
        /// </summary>
        internal static string Donation_Final3 {
            get {
                return ResourceManager.GetString("Donation_Final3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Canadian Gaming Sponsorship - Donation Application Form.
        /// </summary>
        internal static string Donation_PageTitle {
            get {
                return ResourceManager.GetString("Donation_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 1. Name of organization/charity:.
        /// </summary>
        internal static string Donation_Q1 {
            get {
                return ResourceManager.GetString("Donation_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 10. Please specify the amount or value of your request:.
        /// </summary>
        internal static string Donation_Q10 {
            get {
                return ResourceManager.GetString("Donation_Q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Have you received a donation from Great Canadian Gaming Corporation or any of the following properties in the past? Do you have a current request in at other properties?&lt;br /&gt;
        ///    Please indicate which ones:.
        /// </summary>
        internal static string Donation_Q11 {
            get {
                return ResourceManager.GetString("Donation_Q11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Support.
        /// </summary>
        internal static string Donation_Q11Current {
            get {
                return ResourceManager.GetString("Donation_Q11Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Support.
        /// </summary>
        internal static string Donation_Q11Past {
            get {
                return ResourceManager.GetString("Donation_Q11Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. When &amp; what type of support did you receive in the past or what support request do you already have under consideration, if any?.
        /// </summary>
        internal static string Donation_Q12 {
            get {
                return ResourceManager.GetString("Donation_Q12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 13. Please provide a brief description of your organization:.
        /// </summary>
        internal static string Donation_Q13 {
            get {
                return ResourceManager.GetString("Donation_Q13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 14. Please provide a brief description of the event/program for which you are seeking a donation/sponsorship:.
        /// </summary>
        internal static string Donation_Q14 {
            get {
                return ResourceManager.GetString("Donation_Q14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like to find out if Great Canadian can support your organization? Please fill out and submit this application form..
        /// </summary>
        internal static string Donation_Q1Title {
            get {
                return ResourceManager.GetString("Donation_Q1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 2. Is your organization a registered charity?.
        /// </summary>
        internal static string Donation_Q2 {
            get {
                return ResourceManager.GetString("Donation_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. If Yes, please provide the charity license number:.
        /// </summary>
        internal static string Donation_Q3 {
            get {
                return ResourceManager.GetString("Donation_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. If No, what kind of organization are you? (School PAC, Nor-for-profit Org, Community Group, etc.).
        /// </summary>
        internal static string Donation_Q4 {
            get {
                return ResourceManager.GetString("Donation_Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Contact Email Address:.
        /// </summary>
        internal static string Donation_Q5ContactEmail {
            get {
                return ResourceManager.GetString("Donation_Q5ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Contact Name:.
        /// </summary>
        internal static string Donation_Q5ContactName {
            get {
                return ResourceManager.GetString("Donation_Q5ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Contact Telephone Number:.
        /// </summary>
        internal static string Donation_Q5ContactPhone {
            get {
                return ResourceManager.GetString("Donation_Q5ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Contact Title:.
        /// </summary>
        internal static string Donation_Q5ContactTitle {
            get {
                return ResourceManager.GetString("Donation_Q5ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 5. Contact Information:.
        /// </summary>
        internal static string Donation_Q5Title {
            get {
                return ResourceManager.GetString("Donation_Q5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *City / Town:.
        /// </summary>
        internal static string Donation_Q6City {
            get {
                return ResourceManager.GetString("Donation_Q6City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Postal Code:.
        /// </summary>
        internal static string Donation_Q6Postal {
            get {
                return ResourceManager.GetString("Donation_Q6Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Province:.
        /// </summary>
        internal static string Donation_Q6Province {
            get {
                return ResourceManager.GetString("Donation_Q6Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Street address:.
        /// </summary>
        internal static string Donation_Q6Street {
            get {
                return ResourceManager.GetString("Donation_Q6Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 6. Mailing address of organization / charity:.
        /// </summary>
        internal static string Donation_Q6Title {
            get {
                return ResourceManager.GetString("Donation_Q6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 7. Main telephone number for organization / charity.
        /// </summary>
        internal static string Donation_Q7 {
            get {
                return ResourceManager.GetString("Donation_Q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Website link (if applicable):.
        /// </summary>
        internal static string Donation_Q8 {
            get {
                return ResourceManager.GetString("Donation_Q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;DONATION.
        /// </summary>
        internal static string Donation_Q9Donation {
            get {
                return ResourceManager.GetString("Donation_Q9Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;OTHER.
        /// </summary>
        internal static string Donation_Q9Other {
            get {
                return ResourceManager.GetString("Donation_Q9Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If OTHER, please describe:.
        /// </summary>
        internal static string Donation_Q9OtherTitle {
            get {
                return ResourceManager.GetString("Donation_Q9OtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;SPONSORSHIP.
        /// </summary>
        internal static string Donation_Q9Sponsor {
            get {
                return ResourceManager.GetString("Donation_Q9Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 9. Are you seeking:.
        /// </summary>
        internal static string Donation_Q9Title {
            get {
                return ResourceManager.GetString("Donation_Q9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Page1_EmailAddress {
            get {
                return ResourceManager.GetString("Page1_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the guest&apos;s email below. This is optional..
        /// </summary>
        internal static string Page1_EnterEmail {
            get {
                return ResourceManager.GetString("Page1_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was the guest contacted?.
        /// </summary>
        internal static string Page1_Question1 {
            get {
                return ResourceManager.GetString("Page1_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Person.
        /// </summary>
        internal static string Page1_Question1_1 {
            get {
                return ResourceManager.GetString("Page1_Question1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Page1_Question1_2 {
            get {
                return ResourceManager.GetString("Page1_Question1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help us direct your request to the right person, please identify which area of operations your request relates to.
        /// </summary>
        internal static string Page1_Question2B {
            get {
                return ResourceManager.GetString("Page1_Question2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario Operations.
        /// </summary>
        internal static string Page1_Question2B_1 {
            get {
                return ResourceManager.GetString("Page1_Question2B_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia &amp; New Brunswick Operations.
        /// </summary>
        internal static string Page1_Question2B_2 {
            get {
                return ResourceManager.GetString("Page1_Question2B_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia Operations.
        /// </summary>
        internal static string Page1_Question2B_3 {
            get {
                return ResourceManager.GetString("Page1_Question2B_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washington State Operations.
        /// </summary>
        internal static string Page1_Question2B_4 {
            get {
                return ResourceManager.GetString("Page1_Question2B_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Office.
        /// </summary>
        internal static string Page1_Question2B_5 {
            get {
                return ResourceManager.GetString("Page1_Question2B_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specific Property.
        /// </summary>
        internal static string Page1_Question2_1 {
            get {
                return ResourceManager.GetString("Page1_Question2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great American Casino.
        /// </summary>
        internal static string Page1_Question2_10 {
            get {
                return ResourceManager.GetString("Page1_Question2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Rock Casino Vancouver.
        /// </summary>
        internal static string Page1_Question2_11 {
            get {
                return ResourceManager.GetString("Page1_Question2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastings Racetrack &amp; Casino.
        /// </summary>
        internal static string Page1_Question2_12 {
            get {
                return ResourceManager.GetString("Page1_Question2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Rock Casino Resort.
        /// </summary>
        internal static string Page1_Question2_13 {
            get {
                return ResourceManager.GetString("Page1_Question2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorelines Casino Thousand Islands.
        /// </summary>
        internal static string Page1_Question2_14 {
            get {
                return ResourceManager.GetString("Page1_Question2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorelines Slots at Kawartha Downs.
        /// </summary>
        internal static string Page1_Question2_15 {
            get {
                return ResourceManager.GetString("Page1_Question2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Royal Casino.
        /// </summary>
        internal static string Page1_Question2_16 {
            get {
                return ResourceManager.GetString("Page1_Question2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino New Brunswick.
        /// </summary>
        internal static string Page1_Question2_17 {
            get {
                return ResourceManager.GetString("Page1_Question2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorelines Casino Belleville.
        /// </summary>
        internal static string Page1_Question2_18 {
            get {
                return ResourceManager.GetString("Page1_Question2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Nanaimo.
        /// </summary>
        internal static string Page1_Question2_2 {
            get {
                return ResourceManager.GetString("Page1_Question2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Nova Scotia - Halifax.
        /// </summary>
        internal static string Page1_Question2_3 {
            get {
                return ResourceManager.GetString("Page1_Question2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Nova Scotia - Sydney.
        /// </summary>
        internal static string Page1_Question2_4 {
            get {
                return ResourceManager.GetString("Page1_Question2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances Chilliwack.
        /// </summary>
        internal static string Page1_Question2_5 {
            get {
                return ResourceManager.GetString("Page1_Question2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances Dawson Creek.
        /// </summary>
        internal static string Page1_Question2_6 {
            get {
                return ResourceManager.GetString("Page1_Question2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances Maple Ridge.
        /// </summary>
        internal static string Page1_Question2_7 {
            get {
                return ResourceManager.GetString("Page1_Question2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements Casino.
        /// </summary>
        internal static string Page1_Question2_8 {
            get {
                return ResourceManager.GetString("Page1_Question2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraser Downs Racetrack &amp; Casino.
        /// </summary>
        internal static string Page1_Question2_9 {
            get {
                return ResourceManager.GetString("Page1_Question2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select which property you would like to provide feedback for.
        /// </summary>
        internal static string Page1_SelectProperty {
            get {
                return ResourceManager.GetString("Page1_SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        internal static string Page1_StaffName {
            get {
                return ResourceManager.GetString("Page1_StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start the feedback process, please enter your email address below. Your email address will be used for tracking &amp; reporting purposes only..
        /// </summary>
        internal static string Page1_StartFeedback {
            get {
                return ResourceManager.GetString("Page1_StartFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting.
        /// </summary>
        internal static string Page1_Thankyou {
            get {
                return ResourceManager.GetString("Page1_Thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which Great American Casino location did you &lt;u&gt;last&lt;/u&gt; visit?.
        /// </summary>
        internal static string Page2_Question1 {
            get {
                return ResourceManager.GetString("Page2_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. What type of feedback do you want to give?.
        /// </summary>
        internal static string Page2_Question2 {
            get {
                return ResourceManager.GetString("Page2_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        internal static string Page2_Question2_1 {
            get {
                return ResourceManager.GetString("Page2_Question2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string Page2_Question2_2 {
            get {
                return ResourceManager.GetString("Page2_Question2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer a compliment.
        /// </summary>
        internal static string Page2_Question2_3 {
            get {
                return ResourceManager.GetString("Page2_Question2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest an improvement.
        /// </summary>
        internal static string Page2_Question2_4 {
            get {
                return ResourceManager.GetString("Page2_Question2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for Donation / Support.
        /// </summary>
        internal static string Page2_Question2_5 {
            get {
                return ResourceManager.GetString("Page2_Question2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbspEverett.
        /// </summary>
        internal static string Page2_Radio1 {
            get {
                return ResourceManager.GetString("Page2_Radio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbspLakewood.
        /// </summary>
        internal static string Page2_Radio2 {
            get {
                return ResourceManager.GetString("Page2_Radio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbspTukwila.
        /// </summary>
        internal static string Page2_Radio3 {
            get {
                return ResourceManager.GetString("Page2_Radio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbspDeMoines.
        /// </summary>
        internal static string Page2_Radio4 {
            get {
                return ResourceManager.GetString("Page2_Radio4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. What part of our business does this relate to?.
        /// </summary>
        internal static string Page3_Question1 {
            get {
                return ResourceManager.GetString("Page3_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        internal static string Page3_Question1_1 {
            get {
                return ResourceManager.GetString("Page3_Question1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Services.
        /// </summary>
        internal static string Page3_Question1_10 {
            get {
                return ResourceManager.GetString("Page3_Question1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string Page3_Question1_11 {
            get {
                return ResourceManager.GetString("Page3_Question1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing &amp; Promotions.
        /// </summary>
        internal static string Page3_Question1_12 {
            get {
                return ResourceManager.GetString("Page3_Question1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Sales / Catering / Events.
        /// </summary>
        internal static string Page3_Question1_13 {
            get {
                return ResourceManager.GetString("Page3_Question1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorship Request.
        /// </summary>
        internal static string Page3_Question1_14 {
            get {
                return ResourceManager.GetString("Page3_Question1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Gaming.
        /// </summary>
        internal static string Page3_Question1_15 {
            get {
                return ResourceManager.GetString("Page3_Question1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Relations.
        /// </summary>
        internal static string Page3_Question1_16 {
            get {
                return ResourceManager.GetString("Page3_Question1_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Requests &amp; Inquiries.
        /// </summary>
        internal static string Page3_Question1_17 {
            get {
                return ResourceManager.GetString("Page3_Question1_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Page3_Question1_18 {
            get {
                return ResourceManager.GetString("Page3_Question1_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Games / Poker.
        /// </summary>
        internal static string Page3_Question1_2 {
            get {
                return ResourceManager.GetString("Page3_Question1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        internal static string Page3_Question1_3 {
            get {
                return ResourceManager.GetString("Page3_Question1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Beverage.
        /// </summary>
        internal static string Page3_Question1_4 {
            get {
                return ResourceManager.GetString("Page3_Question1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string Page3_Question1_5 {
            get {
                return ResourceManager.GetString("Page3_Question1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Page3_Question1_6 {
            get {
                return ResourceManager.GetString("Page3_Question1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racebook.
        /// </summary>
        internal static string Page3_Question1_7 {
            get {
                return ResourceManager.GetString("Page3_Question1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse Racing.
        /// </summary>
        internal static string Page3_Question1_8 {
            get {
                return ResourceManager.GetString("Page3_Question1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcoach.
        /// </summary>
        internal static string Page3_Question1_9 {
            get {
                return ResourceManager.GetString("Page3_Question1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Please provide your feedback or the details of your request below..
        /// </summary>
        internal static string Page3_Question2 {
            get {
                return ResourceManager.GetString("Page3_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Do you have a(n).
        /// </summary>
        internal static string Page3_Question3_Part1 {
            get {
                return ResourceManager.GetString("Page3_Question3_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card? Please provide your.
        /// </summary>
        internal static string Page3_Question3_Part2 {
            get {
                return ResourceManager.GetString("Page3_Question3_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number so that we may better serve you..
        /// </summary>
        internal static string Page3_Question3_Part3 {
            get {
                return ResourceManager.GetString("Page3_Question3_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Would you like casino staff to contact you about your feedback?  Please choose one of the following options.
        /// </summary>
        internal static string Page3_Question4 {
            get {
                return ResourceManager.GetString("Page3_Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By e-mail.
        /// </summary>
        internal static string Page3_Question4_1 {
            get {
                return ResourceManager.GetString("Page3_Question4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By telephone.
        /// </summary>
        internal static string Page3_Question4_2 {
            get {
                return ResourceManager.GetString("Page3_Question4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not want to be contacted.
        /// </summary>
        internal static string Page3_Question4_3 {
            get {
                return ResourceManager.GetString("Page3_Question4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact E-mail.
        /// </summary>
        internal static string Page4_Email {
            get {
                return ResourceManager.GetString("Page4_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Page4_Name {
            get {
                return ResourceManager.GetString("Page4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide us your contact details. You will only be contacted with respect to your feedback..
        /// </summary>
        internal static string Page4_Question1 {
            get {
                return ResourceManager.GetString("Page4_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel #.
        /// </summary>
        internal static string Page4_Telephone {
            get {
                return ResourceManager.GetString("Page4_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is important to us and we look forward to receiving your comments and will endeavor to answer all questions within 12-24 hours. If your question is more urgent, please contact Guest Services at.
        /// </summary>
        internal static string Page5_Response1 {
            get {
                return ResourceManager.GetString("Page5_Response1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Done&quot; below, you acknowledge that you are aware that your personal information (contact information and feedback) is being collected and used by Great American Gaming (GAG) in accordance with applicable Freedom of Information and Protection of Privacy laws. It will only be used for GAG&apos;s reporting &amp; research purposes and to administer the guest feedback process..
        /// </summary>
        internal static string Page5_Response1_2 {
            get {
                return ResourceManager.GetString("Page5_Response1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information will NOT be sold, shared with third parties, or used for soliciting purposes. If you have any questions about this, please write to GAG at 12715 4th Ave. W. Everett, WA 98204.
        /// </summary>
        internal static string Page5_Response1_3 {
            get {
                return ResourceManager.GetString("Page5_Response1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is important to us and we look forward to receiving your comments and will endeavor to answer all questions within 12-24 hours. If your question is more urgent, please contact Guest Services at.
        /// </summary>
        internal static string Page5_Response2 {
            get {
                return ResourceManager.GetString("Page5_Response2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Done&quot; below, you acknowledge that you are aware that your personal information (contact information and feedback) is being collected and used by Great Canadian Casino Corporation (GCGC) in accordance with applicable Freedom of Information and Protection of Privacy laws. It will only be used for GCGC&apos;s reporting &amp; research purposes and to administer the guest feedback process..
        /// </summary>
        internal static string Page5_Response2_2 {
            get {
                return ResourceManager.GetString("Page5_Response2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information will NOT be sold, shared with third parties, or used for soliciting purposes. If you have any questions about this, please write to GCGC&apos;s Privacy Officer at 95 Schooner Street, Coquitlam, BC V3K 7A8..
        /// </summary>
        internal static string Page5_Response2_3 {
            get {
                return ResourceManager.GetString("Page5_Response2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is important to us and we look forward to receiving your comments and will endeavor to answer all questions within 12-24 hours. If your question is more urgent, please contact Guest Services at.
        /// </summary>
        internal static string Page5_Response3 {
            get {
                return ResourceManager.GetString("Page5_Response3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Done&quot; below, you acknowledge that you are aware that your personal information (contact information and feedback) is being collected and used by Great Canadian Casino Corporation (GCGC) on behalf of BCLC in accordance with British Columbia&apos;s Freedom of Information and Protection of Privacy Act. It will only be used for GCGC&apos;s reporting &amp; research purposes and to administer the guest feedback process..
        /// </summary>
        internal static string Page5_Response3_2 {
            get {
                return ResourceManager.GetString("Page5_Response3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information will NOT be sold, shared with third parties, or used for soliciting purposes. If you have any questions about this, please write to GCGC&apos;s Privacy Officer at 95 Schooner Street, Coquitlam, BC V3K 7A8..
        /// </summary>
        internal static string Page5_Response3_3 {
            get {
                return ResourceManager.GetString("Page5_Response3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string SFeedbackContinueButton {
            get {
                return ResourceManager.GetString("SFeedbackContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string SFeedbackDoneButton {
            get {
                return ResourceManager.GetString("SFeedbackDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Feedback Item.
        /// </summary>
        internal static string SFeedbackGoToItemButton {
            get {
                return ResourceManager.GetString("SFeedbackGoToItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Feedback List.
        /// </summary>
        internal static string SFeedbackGoToListButton {
            get {
                return ResourceManager.GetString("SFeedbackGoToListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Survey List.
        /// </summary>
        internal static string SFeedbackGoToSurveyButton {
            get {
                return ResourceManager.GetString("SFeedbackGoToSurveyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SFeedbackNextButton {
            get {
                return ResourceManager.GetString("SFeedbackNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string SFeedbackOptional {
            get {
                return ResourceManager.GetString("SFeedbackOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string SFeedbackPageTitle {
            get {
                return ResourceManager.GetString("SFeedbackPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string SFeedbackPreviousButton {
            get {
                return ResourceManager.GetString("SFeedbackPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Website.
        /// </summary>
        internal static string SFeedbackReturnButton {
            get {
                return ResourceManager.GetString("SFeedbackReturnButton", resourceCulture);
            }
        }
    }
}
