//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal {
    
    
    public partial class SurveyGSEI {
        
        /// <summary>
        /// mmAcceptGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmAcceptGroup;
        
        /// <summary>
        /// radAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAccept;
        
        /// <summary>
        /// radDecline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radDecline;
        
        /// <summary>
        /// radLocation_EC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_EC;
        
        /// <summary>
        /// radLocation_HA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_HA;
        
        /// <summary>
        /// radLocation_None control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_None;
        
        /// <summary>
        /// radLocation_RR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_RR;
        
        /// <summary>
        /// radLocation_HRCV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_HRCV;
        
        /// <summary>
        /// radLocation_None2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_None2;
        
        /// <summary>
        /// radLocation_Lakewood control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_Lakewood;
        
        /// <summary>
        /// radLocation_Tukwila control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_Tukwila;
        
        /// <summary>
        /// radLocation_Everett control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_Everett;
        
        /// <summary>
        /// radLocation_DeMoines control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_DeMoines;
        
        /// <summary>
        /// radLocation_None3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radLocation_None3;
        
        /// <summary>
        /// Q7A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7A;
        
        /// <summary>
        /// Q7B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7B;
        
        /// <summary>
        /// Q7C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7C;
        
        /// <summary>
        /// Q7D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7D;
        
        /// <summary>
        /// Q7E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7E;
        
        /// <summary>
        /// Q7F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7F;
        
        /// <summary>
        /// Q8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.ScaleQuestionControl Q8;
        
        /// <summary>
        /// Q37Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q37Message;
        
        /// <summary>
        /// Q37_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_1;
        
        /// <summary>
        /// Q37_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_2;
        
        /// <summary>
        /// Q37_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_3;
        
        /// <summary>
        /// Q37_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_4;
        
        /// <summary>
        /// Q37_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_5;
        
        /// <summary>
        /// Q37_6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q37_6;
        
        /// <summary>
        /// Q36Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q36Message;
        
        /// <summary>
        /// Q36Male control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q36Male;
        
        /// <summary>
        /// Q36Female control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q36Female;
        
        /// <summary>
        /// mmQ1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmQ1;
        
        /// <summary>
        /// radQ1_Slots control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Slots;
        
        /// <summary>
        /// radQ1_Tables control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Tables;
        
        /// <summary>
        /// radQ1_Poker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Poker;
        
        /// <summary>
        /// radQ1_Food control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Food;
        
        /// <summary>
        /// radQ1_Entertainment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Entertainment;
        
        /// <summary>
        /// radQ1_Hotel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Hotel;
        
        /// <summary>
        /// radQ1_LiveRacing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_LiveRacing;
        
        /// <summary>
        /// radQ1_Racebook control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Racebook;
        
        /// <summary>
        /// radQ1_Bingo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Bingo;
        
        /// <summary>
        /// radQ1_Lottery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_Lottery;
        
        /// <summary>
        /// radQ1_None control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radQ1_None;
        
        /// <summary>
        /// chkQ2_Slots control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Slots;
        
        /// <summary>
        /// chkQ2_Tables control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Tables;
        
        /// <summary>
        /// chkQ2_Poker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Poker;
        
        /// <summary>
        /// chkQ2_Food control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Food;
        
        /// <summary>
        /// chkQ2_Entertainment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Entertainment;
        
        /// <summary>
        /// chkQ2_Hotel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Hotel;
        
        /// <summary>
        /// chkQ2_LiveRacing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_LiveRacing;
        
        /// <summary>
        /// chkQ2_Racebook control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Racebook;
        
        /// <summary>
        /// chkQ2_Bingo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Bingo;
        
        /// <summary>
        /// chkQ2_Lottery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ2_Lottery;
        
        /// <summary>
        /// mmLastPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmLastPage;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GCC_Web_Portal.SurveyMaster Master {
            get {
                return ((GCC_Web_Portal.SurveyMaster)(base.Master));
            }
        }
    }
}
