//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal {
    
    
    public partial class HastingsSurvey {
        
        /// <summary>
        /// mmTxtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmTxtEmail;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtEmail;
        
        /// <summary>
        /// mmAcceptGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmAcceptGroup;
        
        /// <summary>
        /// radAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAccept;
        
        /// <summary>
        /// radDecline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radDecline;
        
        /// <summary>
        /// Q1Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q1Message;
        
        /// <summary>
        /// Q1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q1_1;
        
        /// <summary>
        /// Q1_2to4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q1_2to4;
        
        /// <summary>
        /// Q1_5to9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q1_5to9;
        
        /// <summary>
        /// Q1_10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q1_10;
        
        /// <summary>
        /// Q2Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q2Message;
        
        /// <summary>
        /// Q2_Yes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q2_Yes;
        
        /// <summary>
        /// Q2_No control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q2_No;
        
        /// <summary>
        /// Q3Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q3Message;
        
        /// <summary>
        /// Q3_Yes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q3_Yes;
        
        /// <summary>
        /// Q3_No control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q3_No;
        
        /// <summary>
        /// Q4Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q4Message;
        
        /// <summary>
        /// Q4_Yes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q4_Yes;
        
        /// <summary>
        /// Q4_No control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q4_No;
        
        /// <summary>
        /// Q4_EncoreNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q4_EncoreNumber;
        
        /// <summary>
        /// Q5Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q5Message;
        
        /// <summary>
        /// Q5_Tarmac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_Tarmac;
        
        /// <summary>
        /// Q5_BoxSeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_BoxSeats;
        
        /// <summary>
        /// Q5_GroupPatio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_GroupPatio;
        
        /// <summary>
        /// Q5_MarqueeTent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_MarqueeTent;
        
        /// <summary>
        /// Q5_SilksBuffet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_SilksBuffet;
        
        /// <summary>
        /// Q5_DiamondClub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q5_DiamondClub;
        
        /// <summary>
        /// Q6Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q6Message;
        
        /// <summary>
        /// Q6_Excellent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q6_Excellent;
        
        /// <summary>
        /// Q6_VeryGood control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q6_VeryGood;
        
        /// <summary>
        /// Q6_Good control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q6_Good;
        
        /// <summary>
        /// Q6_Fair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q6_Fair;
        
        /// <summary>
        /// Q6_Poor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q6_Poor;
        
        /// <summary>
        /// Q7Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q7Message;
        
        /// <summary>
        /// Q7_Excellent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q7_Excellent;
        
        /// <summary>
        /// Q7_VeryGood control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q7_VeryGood;
        
        /// <summary>
        /// Q7_Good control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q7_Good;
        
        /// <summary>
        /// Q7_Fair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q7_Fair;
        
        /// <summary>
        /// Q7_Poor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q7_Poor;
        
        /// <summary>
        /// Q8Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q8Message;
        
        /// <summary>
        /// Q8_DefinitelyWould control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q8_DefinitelyWould;
        
        /// <summary>
        /// Q8_ProbablyWould control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q8_ProbablyWould;
        
        /// <summary>
        /// Q8_MightMightNot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q8_MightMightNot;
        
        /// <summary>
        /// Q8_ProbablyWouldNot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q8_ProbablyWouldNot;
        
        /// <summary>
        /// Q8_DefinitelyWouldNot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q8_DefinitelyWouldNot;
        
        /// <summary>
        /// Q9Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q9Message;
        
        /// <summary>
        /// Q9_Male control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q9_Male;
        
        /// <summary>
        /// Q9_Female control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q9_Female;
        
        /// <summary>
        /// Q10Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q10Message;
        
        /// <summary>
        /// Q10_19to24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_19to24;
        
        /// <summary>
        /// Q10_25to34 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_25to34;
        
        /// <summary>
        /// Q10_35to44 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_35to44;
        
        /// <summary>
        /// Q10_45to54 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_45to54;
        
        /// <summary>
        /// Q10_55to64 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_55to64;
        
        /// <summary>
        /// Q10_65orOlder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q10_65orOlder;
        
        /// <summary>
        /// Q11Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager Q11Message;
        
        /// <summary>
        /// Q11_35000 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q11_35000;
        
        /// <summary>
        /// Q11_35000to59999 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q11_35000to59999;
        
        /// <summary>
        /// Q11_60000to89999 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q11_60000to89999;
        
        /// <summary>
        /// Q11_90000 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q11_90000;
        
        /// <summary>
        /// Q11_NoSay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q11_NoSay;
        
        /// <summary>
        /// Q12_PostalCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q12_PostalCode;
        
        /// <summary>
        /// Q13_FirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q13_FirstName;
        
        /// <summary>
        /// Q13_LastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q13_LastName;
        
        /// <summary>
        /// Q13_Email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q13_Email;
        
        /// <summary>
        /// SurveyComplete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager SurveyComplete;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GCC_Web_Portal.SurveyMaster Master {
            get {
                return ((GCC_Web_Portal.SurveyMaster)(base.Master));
            }
        }
    }
}
