//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal {
    
    
    public partial class SurveyHotel {
        
        /// <summary>
        /// mmTxtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmTxtEmail;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtEmail;
        
        /// <summary>
        /// mmAcceptGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmAcceptGroup;
        
        /// <summary>
        /// radAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radAccept;
        
        /// <summary>
        /// radDecline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton radDecline;
        
        /// <summary>
        /// Q1Overall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.ScaleQuestionControl Q1Overall;
        
        /// <summary>
        /// Q1A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1A;
        
        /// <summary>
        /// Q1B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1B;
        
        /// <summary>
        /// Q1C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1C;
        
        /// <summary>
        /// Q1D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1D;
        
        /// <summary>
        /// Q1E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1E;
        
        /// <summary>
        /// Q1F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q1F;
        
        /// <summary>
        /// Q2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q2;
        
        /// <summary>
        /// Q3A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3A;
        
        /// <summary>
        /// Q3B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3B;
        
        /// <summary>
        /// Q3C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3C;
        
        /// <summary>
        /// Q3D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3D;
        
        /// <summary>
        /// Q3E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3E;
        
        /// <summary>
        /// Q3F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3F;
        
        /// <summary>
        /// Q3G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3G;
        
        /// <summary>
        /// Q3H control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3H;
        
        /// <summary>
        /// Q3I control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3I;
        
        /// <summary>
        /// Q3J control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q3J;
        
        /// <summary>
        /// Q4A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q4A;
        
        /// <summary>
        /// Q4B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q4B;
        
        /// <summary>
        /// Q4C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q4C;
        
        /// <summary>
        /// Q5A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q5A;
        
        /// <summary>
        /// Q5B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q5B;
        
        /// <summary>
        /// Q5C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q5C;
        
        /// <summary>
        /// Q5D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q5D;
        
        /// <summary>
        /// txtQ5Amenities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtQ5Amenities;
        
        /// <summary>
        /// Q6Tramonto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6Tramonto;
        
        /// <summary>
        /// Q6TheBuffet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6TheBuffet;
        
        /// <summary>
        /// Q6Curve control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6Curve;
        
        /// <summary>
        /// Q6InRoomDining control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6InRoomDining;
        
        /// <summary>
        /// Q6FitnessCenter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6FitnessCenter;
        
        /// <summary>
        /// Q6PoolHotTub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6PoolHotTub;
        
        /// <summary>
        /// Q6Meeting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6Meeting;
        
        /// <summary>
        /// Q6ValetParking control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6ValetParking;
        
        /// <summary>
        /// Q6Concierge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6Concierge;
        
        /// <summary>
        /// Q6BellDoorService control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q6BellDoorService;
        
        /// <summary>
        /// Q7A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7A;
        
        /// <summary>
        /// Q7B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7B;
        
        /// <summary>
        /// Q7C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7C;
        
        /// <summary>
        /// Q7D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7D;
        
        /// <summary>
        /// Q7E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7E;
        
        /// <summary>
        /// Q7F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7F;
        
        /// <summary>
        /// Q7G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7G;
        
        /// <summary>
        /// Q7H control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7H;
        
        /// <summary>
        /// Q7I control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q7I;
        
        /// <summary>
        /// Q8A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8A;
        
        /// <summary>
        /// Q8B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8B;
        
        /// <summary>
        /// Q8C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8C;
        
        /// <summary>
        /// Q8D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8D;
        
        /// <summary>
        /// Q8E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8E;
        
        /// <summary>
        /// Q8F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q8F;
        
        /// <summary>
        /// Q9A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9A;
        
        /// <summary>
        /// Q9B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9B;
        
        /// <summary>
        /// Q9C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9C;
        
        /// <summary>
        /// Q9D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9D;
        
        /// <summary>
        /// Q9E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9E;
        
        /// <summary>
        /// Q9F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9F;
        
        /// <summary>
        /// Q9G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9G;
        
        /// <summary>
        /// Q9H control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9H;
        
        /// <summary>
        /// Q9I control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q9I;
        
        /// <summary>
        /// Q10A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10A;
        
        /// <summary>
        /// Q10B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10B;
        
        /// <summary>
        /// Q10C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10C;
        
        /// <summary>
        /// Q10D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10D;
        
        /// <summary>
        /// Q10E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10E;
        
        /// <summary>
        /// Q10F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10F;
        
        /// <summary>
        /// Q10G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10G;
        
        /// <summary>
        /// Q10H control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q10H;
        
        /// <summary>
        /// Q11A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q11A;
        
        /// <summary>
        /// Q11B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q11B;
        
        /// <summary>
        /// Q11C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q11C;
        
        /// <summary>
        /// Q11D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q11D;
        
        /// <summary>
        /// Q12A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q12A;
        
        /// <summary>
        /// Q12B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q12B;
        
        /// <summary>
        /// Q12C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q12C;
        
        /// <summary>
        /// Q12D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q12D;
        
        /// <summary>
        /// Q12E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q12E;
        
        /// <summary>
        /// txtQ13_MeetingDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtQ13_MeetingDescription;
        
        /// <summary>
        /// Q13A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13A;
        
        /// <summary>
        /// Q13B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13B;
        
        /// <summary>
        /// Q13C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13C;
        
        /// <summary>
        /// Q13D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13D;
        
        /// <summary>
        /// Q13E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13E;
        
        /// <summary>
        /// Q13F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13F;
        
        /// <summary>
        /// Q13G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q13G;
        
        /// <summary>
        /// Q14A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14A;
        
        /// <summary>
        /// Q14B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14B;
        
        /// <summary>
        /// Q14C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14C;
        
        /// <summary>
        /// Q14D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14D;
        
        /// <summary>
        /// Q14E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14E;
        
        /// <summary>
        /// Q14F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14F;
        
        /// <summary>
        /// Q14G control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q14G;
        
        /// <summary>
        /// Q15A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q15A;
        
        /// <summary>
        /// Q15B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q15B;
        
        /// <summary>
        /// Q15C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q15C;
        
        /// <summary>
        /// Q15D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q15D;
        
        /// <summary>
        /// Q15E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q15E;
        
        /// <summary>
        /// Q16A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16A;
        
        /// <summary>
        /// Q16B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16B;
        
        /// <summary>
        /// Q16C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16C;
        
        /// <summary>
        /// Q16D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16D;
        
        /// <summary>
        /// Q16E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16E;
        
        /// <summary>
        /// Q16F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q16F;
        
        /// <summary>
        /// Q17A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q17A;
        
        /// <summary>
        /// Q17B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q17B;
        
        /// <summary>
        /// Q17C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q17C;
        
        /// <summary>
        /// Q18A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q18A;
        
        /// <summary>
        /// Q18B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q18B;
        
        /// <summary>
        /// Q19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.TriQuestionRowControl Q19;
        
        /// <summary>
        /// Q20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.TriQuestionRowControl Q20;
        
        /// <summary>
        /// Q21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q21;
        
        /// <summary>
        /// txtQ21Explanation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtQ21Explanation;
        
        /// <summary>
        /// Q22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.TriQuestionRowControl Q22;
        
        /// <summary>
        /// Q23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q23;
        
        /// <summary>
        /// mmQ24A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmQ24A;
        
        /// <summary>
        /// chkQ24A_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_1;
        
        /// <summary>
        /// chkQ24A_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_2;
        
        /// <summary>
        /// chkQ24A_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_3;
        
        /// <summary>
        /// chkQ24A_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_4;
        
        /// <summary>
        /// chkQ24A_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_5;
        
        /// <summary>
        /// chkQ24A_6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_6;
        
        /// <summary>
        /// chkQ24A_7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_7;
        
        /// <summary>
        /// chkQ24A_8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox chkQ24A_8;
        
        /// <summary>
        /// txtQ24A_OtherExplanation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtQ24A_OtherExplanation;
        
        /// <summary>
        /// Q24B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q24B;
        
        /// <summary>
        /// Q24C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q24C;
        
        /// <summary>
        /// Q24D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.ScaleQuestionControl Q24D;
        
        /// <summary>
        /// Q24E_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q24E_1;
        
        /// <summary>
        /// Q24E_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q24E_2;
        
        /// <summary>
        /// Q24E_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q24E_3;
        
        /// <summary>
        /// Q24E_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q24E_4;
        
        /// <summary>
        /// Q24E_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.QuestionRowControl Q24E_5;
        
        /// <summary>
        /// mmQ25 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmQ25;
        
        /// <summary>
        /// Q25_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_1;
        
        /// <summary>
        /// Q25_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_2;
        
        /// <summary>
        /// Q25_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_3;
        
        /// <summary>
        /// Q25_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_4;
        
        /// <summary>
        /// Q25_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_5;
        
        /// <summary>
        /// Q25_6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_6;
        
        /// <summary>
        /// Q25_7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_7;
        
        /// <summary>
        /// Q25_8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_8;
        
        /// <summary>
        /// Q25_9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_9;
        
        /// <summary>
        /// Q25_10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyRadioButton Q25_10;
        
        /// <summary>
        /// Q25_OtherExplanation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q25_OtherExplanation;
        
        /// <summary>
        /// mmQ26 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmQ26;
        
        /// <summary>
        /// Q26_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox Q26_1;
        
        /// <summary>
        /// Q26_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox Q26_2;
        
        /// <summary>
        /// Q26_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox Q26_3;
        
        /// <summary>
        /// Q26_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyCheckBox Q26_4;
        
        /// <summary>
        /// Q26_OtherExplanation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q26_OtherExplanation;
        
        /// <summary>
        /// Q27 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q27;
        
        /// <summary>
        /// Q28 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox Q28;
        
        /// <summary>
        /// Q29 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GCC_Web_Portal.Controls.YesNoControl Q29;
        
        /// <summary>
        /// txtFirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtFirstName;
        
        /// <summary>
        /// txtLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtLastName;
        
        /// <summary>
        /// txtEmail2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtEmail2;
        
        /// <summary>
        /// txtTelephoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtTelephoneNumber;
        
        /// <summary>
        /// txtFollowupReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.SurveyTextBox txtFollowupReason;
        
        /// <summary>
        /// mmLastPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharedClasses.MessageManager mmLastPage;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GCC_Web_Portal.SurveyMaster Master {
            get {
                return ((GCC_Web_Portal.SurveyMaster)(base.Master));
            }
        }
    }
}
