//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC_Web_Portal {
    
    
    public partial class RespondentProfile {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GCC_Web_Portal.Dashboard Master {
            get {
                return ((GCC_Web_Portal.Dashboard)(base.Master));
            }
        }
    }
}
